### ISSUE TITLE
Suggestion for Kingdoms [1.10/1.11]

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [PaulTDD-MC/Kingdoms#1]
- **Scoreboard per world** (Most people that use Multiverse need this)

(Give points to player) (Remove all points) (Remove an amount of points) (List top 10 richest players) (Checks balance)​
- **Kingdom points** (/rp give [player] [amount], /rp reset [player] [amount], /rp remove [player] [amount], /rp list, /rp check)
- **Kingdom areas** (Kingdom leaders may select an area where their 'faction' home is and this would work for '/k home' after setting '/k sethome'
- **Nobody in the kingdom may open other team member's chests unless they are the leader or co-leader**
- **Ranks**
Leader = Access to everything in the kingdom
Co-Leader = Most access to the kingdom
Rebel = 3/4 access to permissions
Barron = 1/2 access to permissions
Knight = Unlocked access
Viking = default to players joining the kingdom
- **Safezone** (Nobody may claim in this region when set-up, also no fighting), **Warzone**(Nobody may claim in this region, pvp allowed), **Wild**(Claiming land is allowed, pvp is allowed)
- **Kingdom integrated minishop that may be configured**
- **Kingdoms per world so the plugin may not be running in specific worlds listed in the config**
- **Kingdom upgrades** (Power, weapons, points, rp etc.)
- **Skills** (these are like spells or upgrades, players may open a skills shop to make their player more op)
- **/k map** (Shows like in factions, a map displaying if any territories are around and what areas may be claimed)
- **Signs for Kingdom Minishop, Kingdom Upgrades, Kingdom Skills**
- **Sign for:**
[Kingdom]
(Name of Kingdom)
This let's server only OP or players within a kingdom go to their kingdom home
- **Chest protection from invaders at a cost**
[Protected]
Chest is protected from explosions or breaking/opening in anyway unless done by owner or OP player
- **Placeholders for:**
%rp_amount% Shows how much rp a player has
%kingdom_kingdom% Shows name of kingdom player is in
%kingdom_members% Shows amount total in the kingdom
%kingdom_members_online% Shows amount total online players in the kingdom
%kingdom_rank% Shows ranking of a player
%kingdom_ally% Shows total number of kingdoms allied with
%kingdom_zone% Shows location if player is in Safezone, Warzone, Wild, or shows territory name of a kingdom
%kingdom_enemy% Shows amount of total enemy kingdoms
- **Configurable Skills GUI, configurable rp points shop GUI, configurable Kingdom Minishop GUI**

**Comment by PaulTDD-MC** [comment]
What whould you'd like to see in the minishop.
And what whould the points be for?

**Comment by xXSKILLS2015Xx** [comment]
I like to use BossShopPro personally, and the points and the points placeholder could tie into BossShopPro if server owners wanted to make their own shops with items that costed Kingdom rp points. In the Minishop, I'd like to see Gold, Diamond, Iron, Wood, Cobblestone, Water, Lava, Swords, Gear. And a MiniShop.yml so owners can set-up the shop to their liking. Maybe an option of multiple shop pages? Or Shop categories like Armor, Weapons, Tools, Building blocks, Miscellaneous and etc.?

**Comment by PaulTDD-MC** [comment]
I've added it on my To-Do list :)

Thanks for your suggestions!
I'll see what I can do.

**Comment by xXSKILLS2015Xx** [comment]
You are very welcome, hope this helps Kingdoms extend to great opportunities. I enjoy what you've brought to the Spigot community and thought it'd be the best of me to give my share back and send you some input and ideas for expansion :D

**Comment by PaulTDD-MC** [comment]
Oh by the way,
For the rank names, for the time you could just change the prefix.

**Comment by xXSKILLS2015Xx** [comment]
Alright, wanted to thank you again for being such a help. I appreciate you being very open to suggestions and guiding me.

**Comment by xXSKILLS2015Xx** [comment]
## More Ideas for Features and Updates!!

1. Server owners may change configuration settings for **Skills** through a GUI or a **Skills.yml** file
2. Server owners may change configuration settings for **RP Points** through a GUI or the **Config.yml** file
3. Server owners may change configuration settings for **Kingdom MiniShop** through a GUI or a **MiniShop.yml** file
4. /kd open [player] Skills (Force Opens the regular Skills GUI on a player)
5. /kd close [player] Skills (Force Closes the regular Skills GUI on a player)
6. /kd open [player] MiniShop or MS or Shop (Force Opens the regular MiniShop GUI on a player)
7. /kd close [player] MiniShop or MS or Shop (Force Closes the regular MiniShop GUI on a player)
8. /kd open [player] RP (Force Opens the RP Settings GUI on a player)
9. /kd close [player] RP (Force Closes the RP Settings GUI on a player)
10. /kd open [player] ach (Force Opens the regular Achievements GUI on a player)
11. /kd close [player] ach (Force Closes the regular Achievements GUI on a player)
10. /kd rp topleast (Checks 10 poorest players with RP Points)
11. /kd ach (GUI for achievement categories)
12. /kd ach edit (GUI for editing Achievements, Achievement categories, Achievement lores, Achievement names, Achievement goals, Achievement text colors, Achievement display item that represents that achievement in the **/kd ach** GUI,  and finally Achievement rewards through a GUI)

**Comment by PaulTDD-MC** [comment]
Thanks, btw was this the scoreboard you were thinkig about?

**Comment by xXSKILLS2015Xx** [comment]
I haven't updated yet, I'll check it out when I get back. Thank you for taking that suggestion though. I'm sure any scoreboard will be fine. I can leave you a suggestion for scoreboard placeholders, and scoreboard ideas if that would help with updates?

**Comment by PaulTDD-MC** [comment]
Suggestions are always good to have :)

**Comment by xXSKILLS2015Xx** [comment]
1. Kingdom Power (How much claimed land)
2. Kingdom Rankings (Kingdoms may all be ranked depending on how much money they have)
3. /kd rp [kingdom name] #See how much RP Points a kingdom has
4. /kd rp give [kingdom name] [amount] #Players can give RP Points to their own kingdoms only

Player Name: Example
Health: 0
RP Points: 0
Kingdom Name: Example
Kingdom Rank Name: Example
Kingdom Power: 0
Kingdom RP Points: 0 
Kingdom Ranking: 0

**Comment by xXSKILLS2015Xx** [comment]
%kingdom rp% Shows Kingdoms rp
%kingdom power% Shows Kingdoms power
%kingdom leader% Shows who is current kingdom owner/creator

**Comment by xXSKILLS2015Xx** [comment]
## Users File
```
users:
  Player: Name
  Player-UUID: 325235-2352385-081240
    kingdom: default
    rank: default
    rp-points: 0
    kingdom-power: 0
    last-logged-in: 0 Hours 30 Minutes 27 Seconds
    total-time-played-days: 1 Years 2 Months 4 Days
    total-time-played: 127 Hours 46 Minutes 33 Seconds
```

**Comment by PaulTDD-MC** [comment]
I'll see what I can do 😄

**Comment by xXSKILLS2015Xx** [comment]
# Recap of suggestions added

Completed Features = _Italics_ 
Not Completed Features = **Bold**

• _Scoreboard per world (Most people that use Multiverse need this)
(Give points to player) (Remove all points) (Remove an amount of points) (List top 10 richest players) (Checks balance)​_

• **Kingdom points (/rp give [player] [amount], /rp reset [player] [amount], /rp remove [player] [amount], /rp list, /rp check)**
• **Kingdom areas (Kingdom leaders may select an area where their 'faction' home is and this would work for '/k home' after setting '/k sethome'**
• **Nobody in the kingdom may open other team member's chests unless they are the leader or co-leader**
• _Ranks
Leader = Access to everything in the kingdom
Co-Leader = Most access to the kingdom
Rebel = 3/4 access to permissions
Barron = 1/2 access to permissions
Knight = Unlocked access
Viking = default to players joining the kingdom_
• **Safezone (Nobody may claim in this region when set-up, also no fighting), Warzone(Nobody may claim in this region, pvp allowed), Wild(Claiming land is allowed, pvp is allowed)**
• **Kingdom integrated minishop that may be configured**
• _Kingdoms per world so the plugin may not be running in specific worlds listed in the config_
• **Kingdom upgrades (Power, weapons, points, rp etc.)**
• **Skills (these are like spells or upgrades, players may open a skills shop to make their player more op)**
• **/k map (Shows like in factions, a map displaying if any territories are around and what areas may be claimed)**
• **Signs for opening Kingdom Minishop, Kingdom Upgrades, Kingdom Skills, and Kingdom Achievements**
• **Sign for:
[Kingdom]
(Name of Kingdom)
This let's server only OP or players within a kingdom go to their kingdom home**
• **Chest protection from invaders at a cost
[Protected]**
• **Chest is protected from explosions or breaking/opening in anyway unless done by owner or OP player**
• **Placeholders for:
%rp_amount% #Shows how much rp a player has
%kingdom_kingdom% #Shows name of kingdom player is in
%kingdom_members% #Shows amount total in the kingdom
%kingdom_members_online% #Shows amount total online players in the kingdom
%kingdom_rank% #Shows ranking of a player
%kingdom_ally% #Shows total number of kingdoms allied with
%kingdom_zone% #Shows location if player is in Safezone, Warzone, Wild, or shows territory name of a kingdom
%kingdom_enemy% #Shows amount of total enemy kingdoms
%kingdom rp% #Shows Kingdoms RP Points
%kingdom power% #Shows Kingdoms power
%kingdom leader% #Shows who is current kingdom owner/creator**
• **Configurable Skills GUI, configurable rp points shop GUI, configurable Kingdom Minishop GUI**
• **Server owners may change configuration settings for Skills through a GUI or a Skills.yml file**
• **Server owners may change configuration settings for RP Points through a GUI or the Config.yml file**
• **Server owners may change configuration settings for Kingdom MiniShop through a GUI or a MiniShop.yml file**
• **/kd open [player] Skills (Force Opens the regular Skills GUI on a player)**
• **/kd close [player] Skills (Force Closes the regular Skills GUI on a player)**
• **/kd open [player] MiniShop or MS or Shop (Force Opens the regular MiniShop GUI on a player)**
• **/kd close [player] MiniShop or MS or Shop (Force Closes the regular MiniShop GUI on a player)**
• **/kd open [player] RP (Force Opens the RP Settings GUI on a player)**
• **/kd close [player] RP (Force Closes the RP Settings GUI on a player)**
• **/kd open [player] ach (Force Opens the regular Achievements GUI on a player)**
• **/kd close [player] ach (Force Closes the regular Achievements GUI on a player)**
• **/kd rp topleast (Checks 10 poorest players with RP Points)**
• **/kd ach (GUI for achievement categories)**
• **/kd ach edit (GUI for editing Achievements, Achievement categories, Achievement lores, Achievement names, Achievement goals, Achievement text colors, Achievement display item that represents that achievement in the /kd ach GUI, and finally Achievement rewards through a GUI)**
• **Kingdom Power (How much claimed land)**
• **Kingdom Rankings (Kingdoms may all be ranked depending on how much money they have)**
• **/kd rp [kingdom name] #See how much RP Points a kingdom has**
• **/kd rp give [kingdom name] [amount] #Players can give RP Points to their own kingdoms only**
• _Scoreboard:_
Player Name: Example
Health: 0
**Player RP Points: 0**
Kingdom Name: Example
Kingdom Rank Name: Example
**Kingdom Power: 0**
**Kingdom RP Points: 0**
**Kingdom Ranking: 0**
• **Users File:
World Name Here:          #NEW
 Users:
  Player: Name
  Player-UUID: 325235-2352385-081240            #NEW
    kingdom: default
    rank: default
    rp-points: 0                     #NEW
    kingdom-power: 0                        #NEW
    last-logged-in: 0 Hours 30 Minutes 27 Seconds                  #NEW
    total-time-played-days: 1 Years 2 Months 4 Days                 #NEW
    total-time-played: 127 Hours 46 Minutes 33 Seconds`             #NEW**

**Comment by PaulTDD-MC** [comment]
How whould the player get kingdom-points?

**Comment by xXSKILLS2015Xx** [comment]
By killing, turning currency from one plugin to Kingdoms and turning it into kingdom resource points. Also raiding, creating a kingdom, trading, raiding the core of a kingdom (would like to discuss this as another feature), and upgrading the kingdom, getting better and farther into the game and doing more things.
