### ISSUE TITLE
More Configurable Options :)

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [PaulTDD-MC/Kingdoms#2]
# Special Features
- An option in the config.yml 
Example:
`Default config for Kingdoms
Kingdoms settings:

   Let Kingdoms handle the chat
  use-kingdoms-prefix: true

   In which worlds should the plugin be enabled 
  enabled-worlds:
  - world
  - world_nether
  - world_the_end

   Rename all rank names
  rank-names:
    king: king
    duke: duke
    general: general
    soldier: soldier
    peasant: peasant

   How often should the scoreboard update, in seconds
  scoreboard-update: 6

  Date format for the user file
  date-format: dd-MM-yyyy HH:mm:ss

   How should the playtime on the scoreboard display?
  playtime-format: '%days%d, %hours%h, %minutes%m'

   Cooldowns in seconds
  cooldowns:
    kd-spawn: 3600

   Protect all placed chests automatic
  automatic-chest-protection: false

   _Special Stuff:
      // First Line of Teleport Signs
      Kingdom Teleport Signs Prefix: '&7[&5Kingdoms&7]'
     // Second Line of Destination
      Kingdom Teleport Signs Text Color: '&b'
     // First Line of an Protected Chest
      Kingdoms Protected Chest Signs Prefix: '&7[&5Kingdoms&7]'
     // Second Line that colors name of Player who owns the chest
      Kingdoms Protected Chest Signs Text Color: '&7'`_
────────────────────────────────────────────────────────────────

Ideas: [Unplanned Version]
- Option to configure how many protected Chests someone can have per rank or set manually per player or if player does not exist in a kingdom, the default amount of allowed protected chests for everyone.
   Example: 
      Protected Chests:
          // Per rank
          // NOTE: * is a sign for infinite chests
          King: *
          Duke: 5
          General: 4 
          Soldier: 3
          Peasant: 2
         // Default for players
         // The boolean 'true' overrides itself so once disabled, no one is allowed to have protected chests unless configured so above or below in ranks or usernames. This option is also for anyone who is not part of a kingdom.
         Default: true
           Amount: 3
        // Per User Set-Up
        SomeonesName: 3
        // Below is a player's uuid entered manually
        34879-4274-27927: 3
- Permission for Creating Protected Chest Signs
- Permission for Creating Protected Chest Signs as another player by putting player name at second sign line
- Permission to disband a Kingdom as leader
   /kd disband
- Permission to disband Kingdom as Server Admin
   /kd disband _kingdom_name_
- Command to delete already set Kingdom spawn
   /kd delspawn
- Permission to delete Kingdom spawn as Server Admin
  kingdoms.spawn.delete
- Command to delete Kingdom spawn as Server Admin
  /kd delspawn _kingdom_name_

**Comment by PaulTDD-MC** [comment]
Why whould you wan't to reset the spawnpoint, that whould be quitte annoying if a player whould want to teleport to their kingdom, the disband option is quite a cool command. I'll add it right away 😃

**Comment by PaulTDD-MC** [comment]
And for the /kda disband <kingdomname> function. You could just use /kda removekingdom <kingdom>

This currently doesn't support users in that kingdom. But I will update that in the next few days.

**Comment by PaulTDD-MC** [comment]
Added

**Comment by xXSKILLS2015Xx** [comment]
Thank you! Plugin is looking amazing!

**Comment by PaulTDD-MC** [comment]
Thanks 😃
