### ISSUE TITLE
"null" before player names

### ISSUE THREAD

**Issue by LukaDeVrij** [PaulTDD-MC/Kingdoms#5]
I gave them a prefix:

  # Chat prefixes
  prefixes:
    king: '&f[&6&lKoning&f]&8'
    duke: '&f[&2&lHertog&f]&8'
    general: '&f[&c&lGeneraal&f]&8'
    soldier: '&f[&3&lSoldaat&f]&8'
    message: '&f'

Don't worry about the text, its Dutch.

**Comment by PaulTDD-MC** [comment]
You should put the prefixes between " " instead of ' '
